#!/usr/bin/env node
/**
 * Scans public/projects/<slug>/ and writes src/data/screenshots.generated.js:
 *
 *   { '<slug>': { images: [{ src, caption, w, h }], video: { src, poster } | null } }
 *
 * Runs automatically before `npm run build` (see package.json "prebuild").
 * Run it by hand after adding images:  npm run screenshots
 *
 * Captions come from filenames:
 *   03-pos-invoice.webp   → "POS invoice"
 *   m02-dashboard.webp    → "Dashboard (mobile)"
 *   d02-dashboard.webp    → "Dashboard (dark mode)"
 */
import { existsSync, mkdirSync, openSync, readSync, closeSync, readdirSync, statSync, writeFileSync } from 'node:fs'
import { extname, join } from 'node:path'

const ROOT = 'public/projects'
const OUT = 'src/data/screenshots.generated.js'
const IMG = new Set(['.webp', '.png', '.jpg', '.jpeg'])

const ACRONYMS = { pos: 'POS', kds: 'KDS', qr: 'QR', hr: 'HR', id: 'ID', crm: 'CRM', api: 'API', ai: 'AI', gl: 'GL', kpi: 'KPI', pdf: 'PDF', sms: 'SMS', cbt: 'CBT', ptm: 'PTM' }

function caption(file) {
  let name = file.replace(/\.[^.]+$/, '')
  let suffix = ''
  if (/^m\d/.test(name)) { suffix = ' (mobile)'; name = name.slice(1) }
  else if (/^d\d/.test(name)) { suffix = ' (dark mode)'; name = name.slice(1) }
  name = name.replace(/^\d+[-_ ]*/, '')
  const words = name.split(/[-_]+/).filter(Boolean).map((w, i) => {
    if (ACRONYMS[w]) return ACRONYMS[w]
    return i === 0 ? w.charAt(0).toUpperCase() + w.slice(1) : w
  })
  return words.join(' ') + suffix
}

/** Minimal image-dimension reader for PNG / JPEG / WebP. */
function dimensions(path) {
  const fd = openSync(path, 'r')
  const buf = Buffer.alloc(64 * 1024)
  const n = readSync(fd, buf, 0, buf.length, 0)
  closeSync(fd)
  const b = buf.subarray(0, n)

  if (b.toString('ascii', 1, 4) === 'PNG') return { w: b.readUInt32BE(16), h: b.readUInt32BE(20) }

  if (b.toString('ascii', 0, 4) === 'RIFF' && b.toString('ascii', 8, 12) === 'WEBP') {
    const chunk = b.toString('ascii', 12, 16)
    if (chunk === 'VP8X') return { w: 1 + b.readUIntLE(24, 3), h: 1 + b.readUIntLE(27, 3) }
    if (chunk === 'VP8L') {
      const bits = b.readUInt32LE(21)
      return { w: 1 + (bits & 0x3fff), h: 1 + ((bits >> 14) & 0x3fff) }
    }
    if (chunk === 'VP8 ') return { w: b.readUInt16LE(26) & 0x3fff, h: b.readUInt16LE(28) & 0x3fff }
  }

  if (b[0] === 0xff && b[1] === 0xd8) {
    let i = 2
    while (i < b.length) {
      if (b[i] !== 0xff) { i++; continue }
      const marker = b[i + 1]
      if (marker >= 0xc0 && marker <= 0xcf && ![0xc4, 0xc8, 0xcc].includes(marker)) {
        return { h: b.readUInt16BE(i + 5), w: b.readUInt16BE(i + 7) }
      }
      i += 2 + b.readUInt16BE(i + 2)
    }
  }
  return { w: 0, h: 0 }
}

const result = {}
if (existsSync(ROOT)) {
  for (const slug of readdirSync(ROOT).sort()) {
    const dir = join(ROOT, slug)
    if (!statSync(dir).isDirectory()) continue
    const files = readdirSync(dir).sort((a, b) => a.localeCompare(b, undefined, { numeric: true }))
    const images = files
      .filter((f) => IMG.has(extname(f).toLowerCase()) && !f.startsWith('walkthrough-poster'))
      .map((f) => ({ src: `/projects/${slug}/${f}`, caption: caption(f), ...dimensions(join(dir, f)) }))
    const hasVideo = files.includes('walkthrough.mp4')
    const video = hasVideo
      ? { src: `/projects/${slug}/walkthrough.mp4`, poster: files.includes('walkthrough-poster.webp') ? `/projects/${slug}/walkthrough-poster.webp` : (images[0]?.src ?? null) }
      : null
    if (images.length || video) result[slug] = { images, video }
  }
}

mkdirSync('src/data', { recursive: true })
writeFileSync(
  OUT,
  `/* AUTO-GENERATED by scripts/screenshots.mjs — do not edit by hand.\n   Add images to public/projects/<slug>/ and run: npm run screenshots */\nexport const generatedScreenshots = ${JSON.stringify(result, null, 2)}\n`,
)
const total = Object.values(result).reduce((n, p) => n + p.images.length, 0)
console.log(`✓ ${OUT}: ${Object.keys(result).length} projects, ${total} images`)
